<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-T9TC6QDG" failures="1" tests="7" name="com.billhub.qa.testcases.ReasonPageTest" time="55.507" errors="0" timestamp="2024-03-28T18:15:12 IST" skipped="0">
  <testcase classname="com.billhub.qa.testcases.ReasonPageTest" name="addNewReasonWithValidDataTest" time="0.855"/>
  <testcase classname="com.billhub.qa.testcases.ReasonPageTest" name="addNewReasonWithInvalidDataTest" time="24.402"/>
  <testcase classname="com.billhub.qa.testcases.ReasonPageTest" name="addNewReasonWithoutDataTest" time="21.626"/>
  <testcase classname="com.billhub.qa.testcases.ReasonPageTest" name="addNewReasonWithDuplicateDataTest" time="1.866">
    <failure message="Duplicate data was added. expected [false] but found [true]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Duplicate data was added. expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertFalse(Assert.java:79)
at com.billhub.qa.testcases.ReasonPageTest.addNewReasonWithDuplicateDataTest(ReasonPageTest.java:75)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- addNewReasonWithDuplicateDataTest -->
  <testcase classname="com.billhub.qa.testcases.ReasonPageTest" name="updateReasonTest" time="4.637"/>
  <testcase classname="com.billhub.qa.testcases.ReasonPageTest" name="searchByReasonNameTest" time="1.328"/>
  <testcase classname="com.billhub.qa.testcases.ReasonPageTest" name="searchByReasonCodeTest" time="0.793"/>
</testsuite> <!-- com.billhub.qa.testcases.ReasonPageTest -->
